# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - .build

analyzer_rules:
  - all
opt_in_rules:
  - all
disabled_rules:
  - contrasted_opening_brace
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - file_header
  - file_name
  - file_types_order
  - force_unwrapping # FIXME
  - function_parameter_count
  - identifier_name
  - large_tuple
  - missing_docs # FIXME
  - no_grouping_extension
  - no_magic_numbers
  - number_separator
  - one_declaration_per_file
  - period_spacing
  - prefixed_toplevel_constant
  - trailing_closure
  - type_contents_order
  - vertical_whitespace_between_cases

implicit_return:
  included:
    - closure

trailing_comma:
  mandatory_comma: true

line_length:
  ignores_function_declarations: true
  ignores_interpolated_strings: true
