#if !canImport(ObjectiveC)
import XCTest

extension Base32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base32Tests = [
        ("testDecodeNonAlphabetCharacter", testDecodeNonAlphabetCharacter),
        ("testDecodeWithOddPadding", testDecodeWithOddPadding),
        ("testDecodeWithoutPadding", testDecodeWithoutPadding),
        ("testFullAlphabet", testFullAlphabet),
        ("testIncompleteBlocks", testIncompleteBlocks),
        ("testRFC", testRFC),
        ("testStrayBits", testStrayBits),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base32Tests.__allTests__Base32Tests),
    ]
}
#endif
