#if !canImport(ObjectiveC)
import XCTest

extension Base16Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base16Tests = [
        ("testDecodeNonAlphabetCharacter", testDecodeNonAlphabetCharacter),
        ("testDecodePartialBlock", testDecodePartialBlock),
        ("testFullAlphabet", testFullAlphabet),
        ("testRFC", testRFC),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base16Tests.__allTests__Base16Tests),
    ]
}
#endif
